import type { Metadata } from "next";
import Providers from "@/app/providers";
import { ColorSchemeScript } from "@mantine/core";
import React from "react";
import { OpenAPI as ServerOpenAPI } from "@/wrapper/server";
import { OpenAPI as SearchOpenAPI } from "@/wrapper/search";

/**
 * Basic configuration for wrapper services
 */
ServerOpenAPI.BASE = process.env.NEXT_PUBLIC_SERVER_URL!;
ServerOpenAPI.WITH_CREDENTIALS = true;
SearchOpenAPI.BASE = process.env.NEXT_PUBLIC_SEARCH_URL!;

/**
 * Should always be imported BEFORE tailwind.
 */
import "@mantine/core/styles.css";
import "@mantine/tiptap/styles.css";

import "@/components/globals.css";

export const metadata: Metadata = {
    title: "Mantine + Tailwind example",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
                <title>GameNode Admin</title>
            </head>
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
